// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:49ddbe92836d20acaa20ac974a4cb748

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_class(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		PropsClass: map[string]interface{}{"a": true},
		Class:      []string{"b"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<span" + mixinClass(nil, []string{"d"}, map[string]interface{}{"c": true}) + mixinAttr(nil, nil, map[string]interface{}{"a": 1}) + ">\n            test class\n        </span>"
		}},
		P:     options,
		Scope: scope,
	})
}
