// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:4a9b03ddc8724a95312a8a6c197e0552

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_page(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"></meta><title>Title</title></head><body></body></html>"
}
