// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:fd5188e241740d3a1d3ac830758a5e92

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_page(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"></meta><title>Title</title></head><body></body></html>"
}
