// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:0f1f32d975fc3941927983ab0f9205f8

package tplgo

func (r *Render) Component_page(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return "<html lang=\"en\"><head><meta charset=\"UTF-8\"></meta><title>Title</title></head><body></body></html>"
}
