// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:3f21f98f4b4dea99d1892c4f373bdb7b

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_select(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("a", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return r.Component_select(&Options{
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
					return "<ff></ff><xx-option> 133 </xx-option><option value=\"1\"></option><option value=\"2\"></option>"
				}},
				P:     options,
				Scope: scope,
			})
		}},
		P:     options,
		Scope: scope,
	})
}
