// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:a23f968d6a1af275d1c2a63be00201f2

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_svg(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return "<!doctype html><html lang=\"en\"><head></head><body>" + r.Component_svg(&Options{
		Attrs: map[string]string{"height": "90", "version": "1.1", "viewBox": "0 0 32 32", "width": "90", "xmlns": "http://www.w3.org/2000/svg"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<path d=\"M8.019 11.511h5.986v1.496h-5.986v-1.496zM17.995 11.511h5.986v1.496h-5.986v-1.496zM16 19.99c-1.762 0-3.282\n          1.017-4.016 2.494h-1.621c0.821-2.324 3.031-3.991 5.636-3.991s4.815 1.667 5.637\n          3.991h-1.621c-0.734-1.477-2.254-2.494-4.016-2.494zM16 29.966c-2.981 0-5.739-0.942-8.007-2.533l0.939-1.164c2.009\n          1.386 4.442 2.201 7.067 2.201 6.887 0 12.47-5.583 12.47-12.47s-5.583-12.47-12.47-12.47c-6.887 0-12.47 5.583-12.47\n          12.47 0 2.65 0.832 5.102 2.242 7.122l-1.049 1.093c-1.683-2.307-2.689-5.14-2.689-8.215 0-7.713 6.253-13.967\n          13.967-13.967s13.966 6.253 13.966 13.967c-0 7.713-6.253 13.966-13.966 13.966z\"></path>"
		}},
		P:     options,
		Scope: scope,
	}) + "</body></html>"
}
