// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:4e41fc2ad42327d7ba5d0d3fb9e5dbc2

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_text(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return func() string {
				var b strings.Builder

				for index, item := range interface2Slice(scope.Get("list")) {
					b.WriteString(func(xscope *Scope) string {
						scope := extendScope(xscope, map[string]interface{}{
							"$index": index,
							"item":   item,
						})

						return "<div>" + r.Component_slot(&Options{
							Props: map[string]interface{}{"msg": scope.Get("item")},
							Attrs: map[string]string{"name": "abc"},
							Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "\n        备选slot内容\n      " }},
							P:     options,
							Scope: scope,
						}) + r.Component_slot(&Options{
							Attrs: map[string]string{"name": "abcd"},
							Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "\n        备选slot abcd内容\n      " }},
							P:     options,
							Scope: scope,
						}) + r.Component_slot(&Options{
							Attrs: map[string]string{"name": "e"},
							Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "\n        备选slot e内容\n      " }},
							P:     options,
							Scope: scope,
						}) + "</div>"
					}(scope))
				}
				return b.String()
			}()
		}},
		P:     options,
		Scope: scope,
	})
}
