// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:e4d46f1281605c9c9dbf1af4e94c49bc

package tplgo

func (r *Render) Component_text(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.Tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return func() string {
				var c = ""

				for index, item := range interface2Slice(lookInterface(this, "list")) {
					c += func(xdata map[string]interface{}) string {
						this := extendMap(xdata, map[string]interface{}{
							"$index": index,
							"item":   item,
						})

						return "<div>" + r.Component_slot(&Options{
							Props: map[string]interface{}{"msg": lookInterface(this, "item")},
							Attrs: map[string]string{"name": "abc"},
							Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "\n        备选slot内容\n      " }},
							P:     options,
							Data:  this,
						}) + r.Component_slot(&Options{
							Attrs: map[string]string{"name": "abcd"},
							Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "\n        备选slot abcd内容\n      " }},
							P:     options,
							Data:  this,
						}) + "</div>"
					}(this)
				}
				return c
			}()
		}},
		P:    options,
		Data: this,
	})
}
