// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:343727db9b01e59edb82aae5293e418e

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_vtext(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<div>" + interfaceToStr(scope.Get("text"), true) + "</div><div>" + interfaceToStr(scope.Get("html")) + "</div>\n    \"" + interfaceToStr(scope.Get("text"), true) + "\n  "
		}},
		P:     options,
		Scope: scope,
	})
}
