// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:964cbdd57ab9739ece8e0ebfcde60168

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_vtext(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.Tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<div>" + interfaceToStr(lookInterface(this, "text"), true) + "</div><div>" + interfaceToStr(lookInterface(this, "html")) + "</div>\n    \"" + interfaceToStr(lookInterface(this, "text"), true) + "\n  "
		}},
		P:    options,
		Data: this,
	})
}
