// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:d8f065ca78e4e60bec53a33ad130c3f6

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_xattr(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.Tag("div", true, &Options{
		PropsClass: lookInterface(this, "customClass"),
		Props:      map[string]interface{}{"id": "id"},
		Attrs:      map[string]string{"data-src": "//baidu.jpg"},
		Class:      []string{"b"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "\n        test attr\n        <img" + mixinAttr(nil, map[string]string{"alt": "标题"}, map[string]interface{}{"src": interfaceToFunc(lookInterface(this, "img"))(lookInterface(this, "imgUrl"))}) + "></img>"
		}},
		P:    options,
		Data: this,
	})
}
