// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr
// src_hash:bf1eb984808479a8ee4e2aa35821c996

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_xSlot(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.Tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"abc": func(props map[string]interface{}) string {
			this := extendMap(this, map[string]interface{}{"a": props})
			_ = this
			return "<div>\n        我是具名slot props msg: " + interfaceToStr(lookInterface(this, "a", "msg"), true) + "\n        我是具名slot 所属组件属性 age: " + interfaceToStr(lookInterface(this, "age"), true) + "\n      </div>"
		}, "default": func(props map[string]interface{}) string {
			return r.Component_text(&Options{
				Props: map[string]interface{}{"list": lookInterface(this, "list")},
				Slot: map[string]NamedSlotFunc{"abc": func(props map[string]interface{}) string {
					this := extendMap(this, map[string]interface{}{"a": props})
					_ = this
					return "<div>\n        我是具名slot props msg: " + interfaceToStr(lookInterface(this, "a", "msg"), true) + "\n        我是具名slot 所属组件属性 age: " + interfaceToStr(lookInterface(this, "age"), true) + "\n      </div>"
				}, "default": func(props map[string]interface{}) string { return "" }},
				P:    options,
				Data: this,
			})
		}},
		P:    options,
		Data: this,
	})
}
