// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:98555d3a647f6c2e0b7d9303251d7c3d

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_xSlot(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return r.Component_text(&Options{
				Props: map[string]interface{}{"list": scope.Get("list")},
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "" }, "e": func(props map[string]interface{}) string {
					scope := extendScope(scope, map[string]interface{}{"slotProps": props})
					_ = scope
					return "<div>\n        xxe\n      </div>"
				}},
				P:     options,
				Scope: scope,
			})
		}, "e": func(props map[string]interface{}) string {
			scope := extendScope(scope, map[string]interface{}{"slotProps": props})
			_ = scope
			return "<div>\n        xxe\n      </div>"
		}},
		P:     options,
		Scope: scope,
	})
}
