// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:44d8c04da1df3dba25d9b125415c035c

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_xStyle(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		PropsStyle: map[string]interface{}{"color": "#f33"},
		Style:      map[string]string{"font-size": "20px"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<span>" + interfaceToStr(scope.Get("text")) + "</span>"
		}},
		P:     options,
		Scope: scope,
	})
}
