// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:10d93099b97890fc2120ac43d856cf00

package tplgo

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_xStyle(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.Tag("div", true, &Options{
		PropsStyle: map[string]interface{}{"color": "#f33"},
		Style:      map[string]string{"font-size": "20px"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<span>" + interfaceToStr(lookInterface(this, "text")) + "</span>"
		}},
		P:    options,
		Data: this,
	})
}
