// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr

package main

func NewRenderCreator() *RenderCreator {
	r := newRenderCreator()
	r.Components = map[string]ComponentFunc{
		"info": xx_info,
		"page": xx_page,
	}
	return r
}
