// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:567602546344fc3b371cb418cc2f696d

package main

import (
	"strings"
)

type _ strings.Builder

func xx_info(r *Render, w Writer, options *Options) {
	scope := extendScope(r.Global, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	_template(r, w, &Options{
		Slots: map[string]NamedSlotFunc{"default": func(w Writer, props Props) {
			_tag(r, w, "div", true, &Options{
				Style: map[string]string{"text-align": "center"},
				Slots: map[string]NamedSlotFunc{"default": func(w Writer, props Props) {
					w.WriteString("<p style=\"padding: 10px 0; \"" + mixinAttr(nil, nil, map[string]interface{}{"height": interfaceAdd(scope.Get("height"), 1)}) + ">")
					w.WriteString(interfaceToStr(scope.Get("slogan"), true))
					w.WriteString("</p><img" + mixinAttr(nil, map[string]string{"alt": "todo logo", "height": "50px"}, map[string]interface{}{"src": scope.Get("logo")}) + "></img>")
				}},
				P:     options,
				Scope: scope,
			})
		}},
		P:     options,
		Scope: scope,
	})
	return
}
