// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:d0a60819d165cbfd905a05c7b5878bcc

package main

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_info(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		Style: map[string]string{"text-align": "center"},
		Slot: map[string]NamedSlotFunc{"default": func(options *Options) string {
			return "<p style=\"padding: 10px 0; \"" + mixinAttr(nil, nil, map[string]interface{}{"height": interfaceAdd(scope.Get("height"), 1)}) + ">" + interfaceToStr(scope.Get("slogan"), true) + "</p><img" + mixinAttr(nil, map[string]string{"alt": "todo logo", "height": "50px"}, map[string]interface{}{"src": scope.Get("logo")}) + "></img>"
		}},
		P:     options,
		Scope: scope,
	})
}
