// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:97e80137901f733fc21a15e6ea3c09e3

package main

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_info(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.tag("div", true, &Options{
		Style: map[string]string{"text-align": "center"},
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return "<p style=\"padding: 10px 0; \"" + mixinAttr(nil, nil, map[string]interface{}{"height": interfaceAdd(lookInterface(this, "height"), 1)}) + ">" + interfaceToStr(lookInterface(this, "slogan"), true) + "</p><img" + mixinAttr(nil, map[string]string{"alt": "todo logo", "height": "50px"}, map[string]interface{}{"src": lookInterface(this, "logo")}) + "></img>"
		}},
		P:    options,
		Data: this,
	})
}
