// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr

package main

func NewRender() *Render{r:=&Render{}
r.components = map[string]ComponentFunc{"component": r.Component_component,"info": r.Component_info,"page": r.Component_page,"slot": r.Component_slot,"v-on": r.Component_vOn,"vOn": r.Component_vOn,}
return r}