// Code generated by go-vue-ssr: https://github.com/bysir-zl/go-vue-ssr

package main

func (r *Render) Component_page(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return "<html lang=\"zh\"><head><meta charset=\"UTF-8\"></meta><title>" + interfaceToStr(lookInterface(this, "title"), true) + "</title></head><body><h1 style=\"text-align: center; margin-top: 100px; \">" + interfaceToStr(lookInterface(this, "title")) + "</h1>" + r.Component_info(&Options{Props: map[string]interface{}{"logo": lookInterface(this, "logo"), "name": lookInterface(this, "title"), "slogan": lookInterface(this, "slogan")},
		Style:     map[string]string{"padding": "20px"},
		StyleKeys: []string{"padding"},
		Slot:      map[string]namedSlotFunc{"default": func(props map[string]interface{}) string { return "" }},
		P:         options,
	}) + r.Component_vOn(&Options{Props: map[string]interface{}{"msg": "hello event"},
		Slot: map[string]namedSlotFunc{"default": func(props map[string]interface{}) string { return "" }},
		P:    options,
	}) + "</body></html>"
}
