// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:1e1c11fcb606f5e256c80bcd43c30951

package main

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_page(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return "<!doctype html><html lang=\"zh\"><head><meta charset=\"UTF-8\"></meta><title>" + interfaceToStr(scope.Get("title"), true) + "</title></head><body><h1 style=\"text-align: center; margin-top: 100px; \">" + interfaceToStr(scope.Get("title")) + "</h1>" + r.Component_info(&Options{
		Props: map[string]interface{}{"height": interfaceAdd(scope.Get("height"), 1), "logo": scope.Get("logo"), "name": scope.Get("title"), "slogan": scope.Get("slogan")},
		Style: map[string]string{"padding": "20px"},
		Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "" }},
		P:     options,
		Scope: scope,
	}) + "<div info> author: " + interfaceToStr(scope.Get("info", "author"), true) + " " + interfaceToStr(scope.Get("info", interfaceToStr(scope.Get("slogan"))), true) + " " + interfaceToStr([]interface{}{scope.Get("slogan")}, true) + "</div>" + r.Component_vOn(&Options{
		Props: map[string]interface{}{"msg": "hello event"},
		Slot:  map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "" }},
		P:     options,
		Scope: scope,
	}) + r.tag("script", false, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "" }},
		P:    options,
		Directives: []directive{
			{Name: "v-on-handler", Value: nil, Arg: ""},
		},
		Scope: scope,
	}) + "<script>\n    // 为dom添加事件\n    for (var i in vOnBinds) {\n        var item = vOnBinds[i];\n        var dom = document.querySelector('[data-von-' + item.DomSelector + ']')\n        dom.addEventListener(item.Event, function (item, dom) {\n            return function (event) {\n                if (window[item.Func]) {\n                    window[item.Func].call(window, event, ...item.Args)\n                } else {\n                    console.error('not found function: ' + item.Func)\n                }\n            }\n        }(item, dom))\n    }\n\n    function buttonClick(msg) {\n        alert(msg)\n    }\n</script></body></html>"
}
