// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:487b3a6cc47a1c717d85fb6fdaaab35b

package main

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_vOn(options *Options) string {
	this := extendMap(r.Prototype, options.Props)
	_ = this
	return r.tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return r.tag("button", false, &Options{
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "click me to alert msg" }},
				P:    options,
				VonDirectives: []vonDirective{
					{Func: "buttonClick", Args: []interface{}{lookInterface(this, "msg")}, Event: "click"},
				},
				Data: this,
			}) + r.tag("button", false, &Options{
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "click me to alert2 msg" }},
				P:    options,
				VonDirectives: []vonDirective{
					{Func: "buttonClick2", Args: []interface{}{lookInterface(this, "msg")}, Event: "click"},
				},
				Data: this,
			})
		}},
		P:    options,
		Data: this,
	})
}
