// Code generated by go-vue-ssr: https://github.com/zbysir/go-vue-ssr
// src_hash:49d22a21c7a0f0954046ef63b10c0f7e

package main

import (
	"strings"
)

type _ strings.Builder

func (r *Render) Component_vOn(options *Options) string {
	scope := extendScope(r.Global.Scope, options.Props)
	options.Directives.Exec(r, options)
	_ = scope
	return r.tag("div", true, &Options{
		Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string {
			return r.tag("button", false, &Options{
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "click me to alert msg" }},
				P:    options,
				VonDirectives: []vonDirective{
					{Func: "buttonClick", Args: []interface{}{scope.Get("msg")}, Event: "click"},
				},
				Scope: scope,
			}) + r.tag("button", false, &Options{
				Slot: map[string]NamedSlotFunc{"default": func(props map[string]interface{}) string { return "click me to alert2 msg" }},
				P:    options,
				VonDirectives: []vonDirective{
					{Func: "buttonClick2", Args: []interface{}{scope.Get("msg")}, Event: "click"},
				},
				Scope: scope,
			})
		}},
		P:     options,
		Scope: scope,
	})
}
